last fixes and tests
n0byk/short_url pull request #1
Opened 2022-02-14 21:17 UTC by n0byk

2022-02-14 21:18 UTC, n0byk commented
Проблемы с тестами, на все кейсы с передаваемыми параметрами прилетает 400 код , поискал, посмотрел вроде все так но что-то не так ....

2022-02-15 10:24 UTC, Barugoo commented on httpapi/v1/handlers/getUrl_test.go
> +
Не оставляй закомментированный код в репозитории. Он сильно дизориентирует. Не используется - удаляй, если нужно восстановить - у тебя все в гите.

2022-02-15 10:26 UTC, n0byk commented on httpapi/v1/handlers/getUrl_test.go
> +
Да, что-то не заметил когда коммитил

2022-02-15 10:26 UTC, Barugoo commented on httpapi/v1/handlers/getUrl_test.go
> +		//следующий кейс что-то не отрабатывает, кажется все так - но не работает, код вместо 301 прилетает 400
Ты делаешь один и тот же запрос в этих двух кейсах. Почему ты расчитываешь на разный результат?
Я не отвечаю в комментариях к пул-реквесту, на всякий случай предупреждаю. Если есть вопросы - лучше задать их в чатик `_community`

2022-02-15 10:29 UTC, Barugoo commented on httpapi/v1/storage/storage.go
> +	"http://localhost:8080/3e89ffb0-948a-4d2c-9308-e5d57569cf19": "http://ya.ru",
Если ты использовал эти данные для отладки - лучше их удалить. Представь, что твой код сейчас будет выкатываться на продакшн, хардкоженные данные там точно ни к чему.

2022-02-15 10:30 UTC, Barugoo commented on httpapi/v1/storage/storage.go
> +	"http://localhost:8080/3e89ffb0-948a-4d2c-9308-e5d57569cf19": "http://ya.ru",
И да, давай сохранять только последнюю часть урла (которая уникальная строка). Хост сервера у тебя может меняться, нет никакого смысла его хранить.

2022-02-15 10:31 UTC, Barugoo commented on httpapi/v1/storage/storage.go
> +	"http://localhost:8080/3e89ffb0-948a-4d2c-9308-e5d57569cf19": "http://ya.ru",
И да, может быть взять какой-нибудь другой метод генерации рандомных строк? Потому что uuid не такой уж и короткий=)

2022-02-15 10:31 UTC, Barugoo requested changes
Не вижу в пул реквесте правок по третьему инкременту

2022-02-15 11:48 UTC, merged